name: Check copyright headers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  copyright-check:
    runs-on: ubuntu-latest
    name: Check copyright headers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
      - name: check license and headers
        run: |
          go install github.com/google/addlicense@v1.0.0
          addlicense -f LICENSE -c "sparetimecoders" -ignore "**/*.yaml" -ignore "**/*.yml" -ignore ".github/*" -ignore "www/site/**" -y "2019" --check .
