name: "golang-vulnerabilities"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
jobs:
  golang-vulnerabilities:
    name: golang-vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: opzkit/govulncheck-action@914e0763397999f9c7cc3be08b56787060f36dd8 # v1.2.0
        with:
          go-version: 'stable'
          check-latest: true
