name: goamqp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"


jobs:
   build-linux:
    name: build/test on ubuntu-latest
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.x"
          check-latest: true
      - name: Tests
        run: |
          go test -p 1 -mod=readonly -race -v -tags integration -coverprofile=coverage.txt -covermode=atomic -coverpkg=$(go list ./... | tr '\n' , | sed 's/,$//') ./...
          go tool cover -func=coverage.txt
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
          flags: tests
          verbose: true
